with open('Makefile', 'w') as f:
    f.write('CXX = g++\n')
    f.write('CXXFLAGS = -std=c++17 -Wall -Wextra -O3 -Iinclude $(shell pkg-config --cflags opencv4)\n')
    f.write('LDFLAGS = -lGL -lGLU -lglut $(shell pkg-config --libs opencv4)\n\n')
    f.write('SRCS = src/main.cpp \\\n')
    f.write('       src/core/camera.cpp \\\n')
    f.write('       src/render/lighting.cpp \\\n')
    f.write('       src/render/shader.cpp \\\n')
    f.write('       src/render/primitives.cpp \\\n')
    f.write('       src/render/video.cpp \\\n')
    f.write('       src/scene/room.cpp \\\n')
    f.write('       src/scene/stage.cpp \\\n')
    f.write('       src/scene/seats.cpp\n\n')
    f.write('OBJS = $(SRCS:.cpp=.o)\n')
    f.write('TARGET = th\n\n')
    f.write('all: $(TARGET)\n\n')
    f.write('$(TARGET): $(OBJS)\n')
    f.write('\t$(CXX) $(OBJS) -o $(TARGET) $(LDFLAGS)\n\n')
    f.write('%.o: %.cpp\n')
    f.write('\t$(CXX) $(CXXFLAGS) -c $< -o $@\n\n')
    f.write('clean:\n')
    f.write('\trm -f $(OBJS) $(TARGET)\n\n')
    f.write('.PHONY: all clean\n')

